name: Bearer PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  rule_check:
    runs-on: ubuntu-22.04
    continue-on-error: true
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: reviewdog/action-setup@d8a7baabd7f3e8544ee4dbde3ee41d0011c3a93f # v1.5.0
        with:
          reviewdog_version: latest
      # I would like to include the bearer.ignore
      - name: Run Report
        id: report
        uses: bearer/bearer-action@828eeb928ce2f4a7ca5ed57fb8b59508cb8c79bc # v2
        with:
          format: rdjson
          output: rd.json
          diff: true
          config-file: 'bearer.yml'
      - name: Run reviewdog
        if: always()
        env:
          REVIEWDOG_TOKEN: ${{ secrets.REVIEWDOG_TOKEN }}
        run:
          cat rd.json | reviewdog -f=rdjson -reporter=github-pr-check